// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTOENQTWqWTgpQ0WyT4RlfZgpxpOhm_Pw',
    appId: '1:514447200733:web:22b6e35fd20559846a2634',
    messagingSenderId: '514447200733',
    projectId: 'task-buddy-bb1a9',
    authDomain: 'task-buddy-bb1a9.firebaseapp.com',
    databaseURL: 'https://task-buddy-bb1a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-buddy-bb1a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEWH4W5_xAWon_5NuH_IqXRHOJ_sdE9ks',
    appId: '1:514447200733:android:b78b6a101d119f786a2634',
    messagingSenderId: '514447200733',
    projectId: 'task-buddy-bb1a9',
    databaseURL: 'https://task-buddy-bb1a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-buddy-bb1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMkZwca7e8LIusTtCyV8mZiGyEHi5KQc',
    appId: '1:514447200733:ios:3862a4662bc8db6f6a2634',
    messagingSenderId: '514447200733',
    projectId: 'task-buddy-bb1a9',
    databaseURL: 'https://task-buddy-bb1a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-buddy-bb1a9.appspot.com',
    iosBundleId: 'com.example.taskbudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMkZwca7e8LIusTtCyV8mZiGyEHi5KQc',
    appId: '1:514447200733:ios:3862a4662bc8db6f6a2634',
    messagingSenderId: '514447200733',
    projectId: 'task-buddy-bb1a9',
    databaseURL: 'https://task-buddy-bb1a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-buddy-bb1a9.appspot.com',
    iosBundleId: 'com.example.taskbudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTOENQTWqWTgpQ0WyT4RlfZgpxpOhm_Pw',
    appId: '1:514447200733:web:67a5089b576a367e6a2634',
    messagingSenderId: '514447200733',
    projectId: 'task-buddy-bb1a9',
    authDomain: 'task-buddy-bb1a9.firebaseapp.com',
    databaseURL: 'https://task-buddy-bb1a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-buddy-bb1a9.appspot.com',
  );

}